services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://ssyncspace:password@postgres:5432/ssyncspace?schema=public
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_SECRET=your-development-secret-key
      - NEXTAUTH_URL=http://localhost:3000
    # volumes:
    #   - .:/app
    # restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ssyncspace
      POSTGRES_USER: ssyncspace
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
