# Version 0.1

services:
  db:
    # Will use Postgres as the database
    image: postgres:15-alpine
    container_name: SSyncSpace-DB
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB: syncspace
    ports:
      - "5432:5432"
    # Persistent storage
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    # Will use Node.js with Express
    build: ./backend
    container_name: SSyncSpace-Backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/syncspace
      - NODE_ENV=production
    # The backend needs to work with the db
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    # Will use Next.js for the frontend
    build: ./frontend
    container_name: SSyncSpace-Frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # The frontend needs a backend to communicate with
    depends_on:
      - backend
    ports:
      - "3001:3000" # Next.js runs on 3000 inside container
  
  nginx:
    image: nginx:alpine
    container_name: SSyncSpace-Nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    # The nginx needs both frontend and backend to route traffic to
    depends_on:
      - frontend
      - backend

# Persistent storage for Postgres (in case of container removal, no loss)
volumes:
  pgdata: