FROM node:25-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3001

# Generate Prisma Client during build
RUN npx prisma generate

# Start development server
CMD ["npm", "run", "dev"]